### ISSUE TITLE
Deploying blockchain and API to separate apps

### ISSUE THREAD

**Issue by pradel** [stacksfoundation/fly-stacks#1]
Following up from discord :) https://discord.com/channels/621759717756370964/909867922971820102/974706950472364053

**Comment by wileyj** [comment]
what's the desired goal here?
as i understand it, you're trying to have:
1. some external DB (either run as a fly service, or some external managed DB like crunchydata)
2. a fly application for stacks-blockchain-api, using the above DB
3. a second application for the stacks-blockchain, sending events to the above API

it seems doable - but also really fragile. the hardest part here would be knowing how to configure the blockchain and api with each dns name that'll work, ideally using internal address so traffic isn't routed over the internet. 

i can take a stab at this, but i'm not sure when i'll get to it.

**Comment by pradel** [comment]
The goal for me was to be able to scale the API easily without scaling the stacks-blockchain. This is my small (not working) attempt at it https://github.com/pradel/stacks-blockchain-api-deploy-fly-guide/tree/feature/deploy-stacks-blockchain-api

**Comment by wileyj** [comment]
hmm, i see what you're trying to do here.

This could be especially tricky to do:
- if you don't want to run more than 1 blockchain, that single node will be
handling all of the `/v2` traffic from the scalable API nodes
- this requires:
  - "private" network
    - 1 blockchain node (with a known API node to emit events to)
    - 1 API node who only receives events from the blockchain instance and
writes to the managed DB
  - "public" network
    - >0 API nodes that know both the managed DB *and* the "private"
blockchain node
    - all api's must be running in readonly mode
 - what prevents DOS from occurring if `/v2` is spammed with traffic? this
might require another proxy type of application to rate-limit, and all the
other services to run on internal ip's/ports only (would that still allow
the services to talk to each other? not sure).
- the biggest concern i have here is that there is no **easy** way to
recover the data if it's corrupt (it can happen if the provider (fly)
migrates your service to a VM, which shuts down the running service. the
blockchain sometimes requires several minutes to properly stop it's
runloop).

I'm not opposed to giving this a shot, but i think either a different
approach or a different provider would be better suited for what you're
trying to do

**Comment by wileyj** [comment]
To be honest, this sounds like something a tool like cloudformation (on AWS) is built for - and it'll give you more control over the services vs an opaque service like fly. 
I haven't tried similar tools on other providers, but i imagine the process would be very similar.

**Comment by pradel** [comment]
> To be honest, this sounds like something a tool like cloudformation (on AWS) is built for - and it'll give you more control over the services vs an opaque service like fly.

I think you are right, I was evaluating what was the best setup for it and as a Fly user really wanted to have it running there. Definitely agree with all the previous points, will look at other providers to see what I can do, thanks for sharing your thoughts :)

**Comment by wileyj** [comment]
This might be a good use case though to expand ways to run the API. kubesail might be a good target that would be easier for devs to use vs somethings like cloudformation/terraform. 

always open to suggestions - in fact, this repo came about from a suggestion from a dev who wanted to use fly.
